### ISSUE TITLE
AWS Organizations Tagging resources

### ISSUE THREAD

**Issue by rbracewell** [turbot/steampipe-mod-aws-tags#31]
**Is your feature request related to a problem? Please describe.**
Looking at the Steampipe docs I can’t see controls that allow for the querying of tags against Organizational resources, such as

- AWS accounts
- Organizational units
- The organization’s root

These resources support tags are documented per AWS docs https://docs.aws.amazon.com/organizations/latest/userguide/orgs_tagging.html

**Describe the solution you'd like**
Once tables have been added with the tag column controls should be added to surface the additional tag data

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by cbruno10** [comment]
Hi @rbracewell , for the resources you've mentioned, if there is no tag information available in the AWS plugin tables today, we'd need to add them in the AWS plugin.

Can you please open an issue in the AWS plugin repository if this is the case and we can have a closer look? Thanks!
